### ISSUE TITLE
Does not process replay files correctly for bc19 0.3.16

### ISSUE THREAD

**Issue by nikhilsardana** [hgarrereyn/Clairvoyance#1]
I think replay files are processed differently for bc19 version 0.3.16. For example, viewing the replay file below in the official viewer and Clairvoyance show two different games. Clairvoyance shows the castles moving.

[replay.zip](https://github.com/hgarrereyn/Clairvoyance/files/2751785/replay.zip)

**Comment by hgarrereyn** [comment]
As a matter of fact, I just pushed some changes to fix this.

It is caused by the clairvoyance bc19 dependency being outdated. The sidebar should now track versions and tell you if you need to update.

Try running `npm i bc19` in the Clairvoyance directory.
